MODEL:
  NUM_CLASSES: 7
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("custom_train",)
  TEST: ("custom_valid",)
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: 'outputs/custom'